### ISSUE TITLE
Bug in soup?

### ISSUE THREAD

**Issue by twoyoon** [twoyoon/dart_projects#3]
There's a bug int he soup

**Comment by twoyoon** [comment]
ok i'll look into it

**Comment by twoyoon** [comment]
the bug is gone. resolves #2

**Comment by yummypasta** [comment]
I think that the bug ate all of the soup...
So i guess we aren't going to get more soup...
#3 is resolved in a very sad way.

**Comment by yummypasta** [comment]
ISSUE IS CLOSED AND RESOLVED!
